twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        gcategories: '@App\Globals\Categories'
        glicences: '@App\Globals\Licences'
when@test:
    twig:
        strict_variables: true
